### ISSUE TITLE
Invalid shorthand property initializer 

### ISSUE THREAD

**Issue by SarahRourke** [SarahRourke/vets-for-pets#1]
Invalid shorthand property initializer;

services/auth/auth-helpers.js:5;
services/auth/local.js:6:21;

I changed passport.initialize to passport.init and that didn't do anything. 
I have check for a possible missing export/import;
And I have checked for what is missing with LocalStrategy - but not completed that search. 

[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
/Users/sarahrourke/Desktop/vets-for-pets/vets-for-pets/services/auth/auth-helpers.js:5
    comparePass = (userPassword, databasePassword) => {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/sarahrourke/Desktop/vets-for-pets/vets-for-pets/services/auth/local.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[nodemon] app crashed - waiting for file changes before starting...
^C

The error is stating that my shorthand 'init' is not working in order to use the function;
and I have an Object that has not been defined - I am guessing that is LocalStrategy. 

I will know the error is solved when i am able to run my server. Desired outcome is to be able to check efficacy of authorization.

**Comment by jlr7245** [comment]
see comment here! https://github.com/SarahRourke/vets-for-pets/commit/3c451233d6d301aaa2f21db41fe7e83fee46c5ec#r41424238 your `passport.initialize` should stay as `passport.initialize`.

The upwards carets under this

```
comparePass = (userPassword, databasePassword) => {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

are telling you where the error is, so that should be your first place to look!
